name: 早安問候機器人

on:
  schedule:
    # 台灣時間每天早上 08:00 執行 (cron 的時區是 UTC，所以要減 8 小時為 00:00)
    - cron: '0 0 * * *'
  # 允許手動觸發執行
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: 檢索程式碼
        uses: actions/checkout@v6

      - name: 設定 Python 環境
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip' # 快取套件以加速執行

      - name: 安裝相依套件
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 opencc-python-reimplemented cloudinary lxml

      - name: 早安機器人程式
        env:
          # 為了保護隱私，我們將敏感資訊放在 GitHub Secrets
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: python main.py # 假設你的主程式檔名為 main.py
